# Generated by Django 3.0.8 on 2020-07-22 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
        ('user', '0003_user_age'),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='movieList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.CharField(max_length=500)),
                ('movie_name', models.CharField(max_length=100)),
                ('status', models.CharField(default='OK', max_length=100)),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.manager')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user')),
            ],
        ),
        migrations.AddField(
            model_name='movies',
            name='movieList',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.movieList'),
        ),
    ]
