# Generated by Django 3.0.8 on 2020-07-22 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20200722_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielist',
            name='status',
            field=models.CharField(default='ok', max_length=200),
        ),
    ]
