# Generated by Django 3.0.8 on 2020-07-22 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20200722_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='movielist',
            name='title',
            field=models.CharField(default='notavailable', max_length=100),
        ),
        migrations.AddField(
            model_name='movielist',
            name='url',
            field=models.CharField(default='none', max_length=500),
        ),
    ]
