# Generated by Django 3.0.8 on 2020-07-22 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20200722_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielist',
            name='title',
            field=models.CharField(default='notavailable', max_length=500),
        ),
    ]
