# Generated by Django 3.0.8 on 2020-07-22 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20200722_0148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movielist',
            name='title',
        ),
        migrations.RemoveField(
            model_name='movielist',
            name='url',
        ),
    ]
