# Generated by Django 3.0.8 on 2020-07-22 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
        ('user', '0003_user_age'),
        ('movies', '0009_auto_20200722_0153'),
    ]

    operations = [
        migrations.CreateModel(
            name='movieCmnt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=500)),
                ('status', models.CharField(default='ok', max_length=100)),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.manager')),
                ('movieList', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.movieList')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user')),
            ],
        ),
    ]
