# Generated by Django 3.0.8 on 2020-07-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_moviecmnt'),
    ]

    operations = [
        migrations.AddField(
            model_name='movielist',
            name='title',
            field=models.CharField(default='none', max_length=500),
        ),
        migrations.AddField(
            model_name='movielist',
            name='url',
            field=models.CharField(default='none', max_length=500),
        ),
        migrations.DeleteModel(
            name='movies',
        ),
    ]
