# Generated by Django 3.0.8 on 2020-07-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frist_name', models.CharField(default='none', max_length=50)),
                ('last_name', models.CharField(default='none', max_length=50)),
                ('mail_id', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('phone_no', models.CharField(max_length=500)),
                ('message', models.CharField(max_length=500)),
                ('age', models.CharField(default='none', max_length=200)),
                ('Gender', models.CharField(default='none', max_length=200)),
                ('status', models.CharField(default='OK', max_length=200)),
            ],
        ),
    ]
