# Generated by Django 3.0.8 on 2020-07-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Name',
        ),
        migrations.AddField(
            model_name='user',
            name='Gender',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='frist_name',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
